
const paula = document.querySelectorAll('.botaos');


for(let sulfetodepotassiosomadocomasuaprimapodemacabaremumserioeventocatastroficoquepodetematarpoispodesertoxicokkk = 0; sulfetodepotassiosomadocomasuaprimapodemacabaremumserioeventocatastroficoquepodetematarpoispodesertoxicokkk < paula.length; sulfetodepotassiosomadocomasuaprimapodemacabaremumserioeventocatastroficoquepodetematarpoispodesertoxicokkk++){
    console.log(sulfetodepotassiosomadocomasuaprimapodemacabaremumserioeventocatastroficoquepodetematarpoispodesertoxicokkk);
    paula[sulfetodepotassiosomadocomasuaprimapodemacabaremumserioeventocatastroficoquepodetematarpoispodesertoxicokkk].onclick = function() {
        for(let imetarussianinfranceandshewasreallycoolwehadalotoffuntogetherandshegavemehernumberthedayiactuallygetmoneyiwillgotorussiaandwewillbehappy; imetarussianinfranceandshewasreallycoolwehadalotoffuntogetherandshegavemehernumberthedayiactuallygetmoneyiwillgotorussiaandwewillbehappy<paula.length;imetarussianinfranceandshewasreallycoolwehadalotoffuntogetherandshegavemehernumberthedayiactuallygetmoneyiwillgotorussiaandwewillbehappy++){
            paula[imetarussianinfranceandshewasreallycoolwehadalotoffuntogetherandshegavemehernumberthedayiactuallygetmoneyiwillgotorussiaandwewillbehappy].classList.remove('ativo');
        }
        paula[sulfetodepotassiosomadocomasuaprimapodemacabaremumserioeventocatastroficoquepodetematarpoispodesertoxicokkk].classList.add('ativo');
}
}

